name: PR checks
on: pull_request

env:
  SECRET_KEY: insecure_test_key

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag kubeflow-news.com .
      - name: Run image
        run: |
          docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key kubeflow-news.com
          sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost

  run-serve:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Node dependencies
        run: yarn install

      - name: Python dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Build assets
        run: |
          yarn build
          PORT=8035 yarn serve &
          sleep 3
          curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost:8035

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node dependencies
        run: yarn install

      - name: Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node dependencies
        run: yarn install

      - name: Lint python
        run: yarn lint-scss

  test-python:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Node dependencies
        run: yarn install

      - name: Python dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install coverage
        run: sudo pip3 install coverage

      - name: Test python
        run: |
          coverage run  --source=. -m unittest discover tests
          bash <(curl -s https://codecov.io/bash) -cF python
          
  check-inclusive-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
