name: Test docker image
on: pull_request
env:
  DOCKER_BUILDKIT: 1
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build --tag etclite-io .
    - name: Run image
      run: |
        docker run -d -p 80:80 etclite-io
        sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
